### ISSUE TITLE
API key not working from a file that is included in the gitignore 

### ISSUE THREAD

**Issue by AritraBhattacharjee** [AritraBhattacharjee/News-App#2]
I have an API key of the website newsapi.org. I am not willing to show the api key and so i have kept in a seperate file in JS directory and imported from there; and then added the file to .gitgnore. Its working fine in my local machine, but when I uploaded it to the github and tried switchinh on github pages, the content is not loading. It is showing the error "Failed to load resource: the server responded with a status of 404 ()    /News-App/JS/key.js:1  ". To specify, key.js is the file that contains my API key.

Any solution is welcomed and greatly appreciated
@hrittikhere any ideas? How to solve this?

**Comment by hrittikhere** [comment]
@AritraBhattacharjee Github pages support static content and requests going through API aren't static so it falls under dynamic. You can use something like Heroku for your application and add your API key as a secret in environment variables which you can pass to Heroku for setting up a dynamic environment.
